In [1]:
def my_fun():
    print("hello")

In [2]:
my_fun()

hello


In [3]:
def add(a,b):
    print(a+b)

In [4]:
add(3,4)

7


In [19]:
def addv(a,b):
    c=a+b
    return c
addv(3,4)

7

In [22]:
b=[1,2,3,4,5]
print(b)

[1, 2, 3, 4, 5]


In [23]:
b="python full stack"
b.split()

['python', 'full', 'stack']

In [24]:
b="python,full,stack"
ab=b.split(",")
print(ab)

['python', 'full', 'stack']


In [25]:
ab[0]

'python'

In [26]:
k=[1,2,3,4,5]
for i in k:
    print(i)

1
2
3
4
5


In [27]:
for i in range(0,10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [28]:
for i in range(10,0,-1):
    print(i)

10
9
8
7
6
5
4
3
2
1


In [29]:
list1=[]
t=int(input("Enter the size of array"))
for i in range(0,t):
    l=input("Enter the values:")
    list1.append(l)

Enter the size of array3
Enter the values:1
Enter the values:4
Enter the values:6


In [30]:
list1

['1', '4', '6']

In [32]:
from package import pack
pack sum(2,3)

SyntaxError: invalid syntax (Temp/ipykernel_896/811537491.py, line 2)

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
z=np.zeros((2,3))

In [5]:
z

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
r=np.arange(0,10,2)

In [7]:
r

array([0, 2, 4, 6, 8])

In [8]:
a

array([1, 2, 3])

In [9]:
b=np.array([4,5,6])

In [10]:
a+b

array([5, 7, 9])

In [11]:
np.mean(a)

2.0

In [12]:
np.max(a)

3

In [13]:
c=np.array([
    [1,2],
    [3,4]
])

In [14]:
c

array([[1, 2],
       [3, 4]])

In [15]:
d=np.array([
    [4,8],
    [6,9]
])

In [16]:
c+d

array([[ 5, 10],
       [ 9, 13]])

In [17]:
c*d

array([[ 4, 16],
       [18, 36]])

In [18]:
a*b

array([ 4, 10, 18])

In [19]:
e=c*d

In [20]:
e

array([[ 4, 16],
       [18, 36]])

In [21]:
f=np.dot(c,d)
f

array([[16, 26],
       [36, 60]])

In [22]:
c.T

array([[1, 3],
       [2, 4]])

In [23]:
c

array([[1, 2],
       [3, 4]])

In [24]:
d

array([[4, 8],
       [6, 9]])

In [25]:
f=np.dot(c,d)
f

array([[16, 26],
       [36, 60]])

In [26]:
f.T

array([[16, 36],
       [26, 60]])

In [27]:
print("\n matrix 1:\n",c)
print("\n matrix 2:\n",d)
print("\n Addition: \n",c+d)
print("\n substraction: \n",c-d)
print("\n Multiplication(Element wise):\n",c*d)
print("\n Dot Multiplication(row x column):\n",f)
print("\n Transpose:\n",f.T)


 matrix 1:
 [[1 2]
 [3 4]]

 matrix 2:
 [[4 8]
 [6 9]]

 Addition: 
 [[ 5 10]
 [ 9 13]]

 substraction: 
 [[-3 -6]
 [-3 -5]]

 Multiplication(Element wise):
 [[ 4 16]
 [18 36]]

 Dot Multiplication(row x column):
 [[16 26]
 [36 60]]

 Transpose:
 [[16 36]
 [26 60]]
